run-name: 'コンテナのビルドとpush'
on: [push]
jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: QEMUのセットアップ
        uses: docker/setup-qemu-action@v2

      - name: Dockerのセットアップ
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
          platforms: linux/arm64

      - name: Dockerのイメージレイヤーキャッシュ
        uses: actions/cache@v2
        id: cache-package
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Dockerレジストリへのログイン
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: SHA256の取得
        id: get_sha
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: ビルド&プッシュ (app1)
        uses: ./.github/actions/build-push
        with:
          registory_url: oriishitakahiro
          app_name: app1
          tags: "${{ env.COMMIT_SHA }},${{ github.ref_name }},latest"
